### ISSUE TITLE
Heartbeat error occurs after 90 seconds

### ISSUE THREAD

**Issue by Galoshi** [ifm/o2x5xx-python#45]
Customer told me that following error still exists/occurs after 90 seconds...

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 1401, in run
    self.function(*self.args, **self.kwargs)
  File "/home/xxx/xxx/.venv/lib/python3.11/site-packages/o2x5xx/rpc/proxy.py", line 133, in doAutoHeartbeat
    newHeartbeatInterval = self.heartbeat(self.autoHeartbeatInterval)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/xxx/.venv/lib/python3.11/site-packages/o2x5xx/rpc/proxy.py", line 123, in heartbeat
    result = self.proxy.heartbeat(heartbeatInterval)
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'heartbeat'

**Comment by Galoshi** [comment]
Seems like this is fixed in 0.4.2-pre.
Will be closed!
